formatter: 'markdown table'

sections:
  hide:
    - 'data-sources'
    # No external modules are used, would otherwise show an empty section
    - 'modules'
    - 'resources'

settings:
  anchor: false
